import time
from selenium import webdriver
from selenium.webdriver.common.by import By
chrome_driver = webdriver.Chrome()
chrome_driver.get("https://opensource-demo.orangehrmlive.com/")
time.sleep(5)
chrome_driver.find_element(By.XPATH, value ="//input[@name='username']").send_keys("Admin")
password = "admin123"
chrome_driver.find_element(By.XPATH, value ="//input[@name='password']").send_keys(password)
login = chrome_driver.find_element(By.XPATH, value="//button[@type='submit']")
login.click()
time.sleep(5)
admin = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/aside/nav/div[2]/ul/li[1]/a")
admin.click()
time.sleep(4)
usermanagament  = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[1]/span/i")
usermanagament.click()
time.sleep(4)
user = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[1]/ul/li")
user.click()
time.sleep(4)
job = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[2]/span/i")
job.click()
time.sleep(4)
jobtitle = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[2]/ul/li[1]/a")
jobtitle.click()
time.sleep(4)
job = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[2]/span/i")
job.click()
time.sleep(4)
paygrades = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[2]/ul/li[2]/a")
paygrades.click()
time.sleep(4)
job = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[2]/span/i")
job.click()
time.sleep(4)
status =  chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[2]/ul/li[3]/a")
status.click()
time.sleep(4)
job = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[2]/span/i")
job.click()
time.sleep(4)
categories = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[2]/ul/li[4]/a")
categories.click()
time.sleep(4)
job = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[2]/span/i")
job.click()
time.sleep(4)
shifts = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[2]/ul/li[5]/a")
shifts.click()
time.sleep(4)
oraganization = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[3]/span/i")
oraganization.click()
time.sleep(4)
info = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[3]/ul/li[1]/a")
info.click()
time.sleep(4)
oraganization = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[3]/span/i")
oraganization.click()
time.sleep(4)
location = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[3]/ul/li[2]/a")
location.click()
time.sleep(4)
oraganization = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[3]/span/i")
oraganization.click()
time.sleep(4)
structure = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[3]/ul/li[3]/a")
structure.click()
time.sleep(4)
qualification = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[4]/span")
qualification.click()
time.sleep(4)
skills = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[4]/ul/li[1]/a")
skills.click()
time.sleep(4)
qualification = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[4]/span")
qualification.click()
time.sleep(4)
education = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[4]/ul/li[2]/a")
education.click()
time.sleep(4)
qualification = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[4]/span")
qualification.click()
time.sleep(4)
license = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[4]/ul/li[3]/a")
license.click()
time.sleep(4)
qualification = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[4]/span")
qualification.click()
time.sleep(4)
languages = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[4]/ul/li[4]/a")
languages.click()
time.sleep(4)
qualification = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[4]/span")
qualification.click()
time.sleep(4)
membership = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[4]/ul/li[5]/a")
membership.click()
time.sleep(4)
more = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[5]/span")
more.click()
time.sleep(4)
nation = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[5]/ul/div[1]/li/a")
nation.click()
time.sleep(5)
more = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[5]/span")
more.click()
time.sleep(4)
branding = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[5]/ul/div[2]/li/a")
branding.click()
time.sleep(4)
more = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[5]/span")
more.click()
time.sleep(4)
configuration = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[5]/ul/div[3]/li/a")
configuration.click()
time.sleep(4)
mail = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[5]/ul/div[3]/ul/li[1]/a")
mail.click()
time.sleep(4)
more = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[5]/span")
more.click()
time.sleep(4)
configuration = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[5]/ul/div[3]/li/a")
configuration.click()
time.sleep(4)
subs = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[5]/ul/div[3]/ul/li[2]/a")
subs.click()
time.sleep(4)
more = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[5]/span")
more.click()
time.sleep(4)
configuration = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[5]/ul/div[3]/li/a")
configuration.click()
time.sleep(4)
local = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[5]/ul/div[3]/ul/li[3]/a")
local.click()
time.sleep(4)
more = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[5]/span")
more.click()
time.sleep(4)
configuration = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[5]/ul/div[3]/li/a")
configuration.click()
time.sleep(4)
pack = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[5]/ul/div[3]/ul/li[4]/a")
pack.click()
time.sleep(4)
more = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[5]/span")
more.click()
time.sleep(4)
configuration = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[5]/ul/div[3]/li/a")
configuration.click()
time.sleep(4)
mode = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[5]/ul/div[3]/ul/li[5]/a")
mode.click()
time.sleep(4)
more = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[5]/span")
more.click()
time.sleep(4)
configuration = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[5]/ul/div[3]/li/a")
configuration.click()
time.sleep(4)
media = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[5]/ul/div[3]/ul/li[6]/a")
media.click()
time.sleep(4)
more = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[5]/span")
more.click()
time.sleep(4)
configuration = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[5]/ul/div[3]/li/a")
configuration.click()
time.sleep(4)
register = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[5]/ul/div[3]/ul/li[7]/a")
register.click()
time.sleep(4)
more = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[5]/span")
more.click()
time.sleep(4)
configuration = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[5]/ul/div[3]/li/a")
configuration.click()
time.sleep(4)
ldap = chrome_driver.find_element(By.XPATH, value="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[5]/ul/div[3]/ul/li[8]/a")
ldap.click()
time.sleep(4)





